### ISSUE TITLE
Java client requires delay after `ClientChannel::enable`

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/rodbus#147]
I'm using the Java bindings to write an interoperability unit test with my own Modbus TLS implementation and I've found that if I don't insert a sleep call between `ClientChannel::enable` and attempting to use the channel it throws an Exception like this:

```
io.stepfunc.rodbus.RequestException: NO_CONNECTION
java.util.concurrent.CompletionException: io.stepfunc.rodbus.RequestException: NO_CONNECTION
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at StepfuncInteropTest.readWriteClient(StepfuncInteropTest.kt:146)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: io.stepfunc.rodbus.RequestException: NO_CONNECTION
	at app//io.stepfunc.rodbus.ClientChannel$1.onFailure(ClientChannel.java:105)
```

Code is something like:
```
// ... set up channel
channel.enable()

// doesn't work with this commented out
Thread.sleep(1000)

assertDoesNotThrow {
    val cs: CompletionStage<List<BitValue>> = channel.readCoils(
        RequestParam(ubyte(1), Duration.ofSeconds(2)),
        AddressRange(ushort(0), ushort(1))
    )
    val values: List<BitValue> = cs.toCompletableFuture().join()
    println(values.joinToString { "i=${it.index}, v=${it.value}" })
}
```

**Comment by jadamcrain** [comment]
This is expected behavior. The client will fail any requests until a TCP or TLS connection is actually established. The request made after `enable` is just racing with the connect operation.

If you want to make your tests event-driven instead of requiring a sleep, you can listen for the [ClientState](https://docs.stepfunc.io/rodbus/1.4.0/java/io/stepfunc/rodbus/ClientStateListener.html) to become `CONNECTED`. Just have your implementation read client state events from a BlockingQueue, and then start doing operations after that to ensure you're connected.
